In [51]:
import pandas as pd
import math

In [15]:
url = "http://www.pro-football-reference.com/teams/nwe/2016.htm"
nwe = pd.read_html(url)

In [22]:
nwe[0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Tot Yds & TO,Unnamed: 4,Unnamed: 5,Passing,Rushing,Penalties,Unnamed: 9,...,Yds.3,1stPy,#Dr,Sc%,TO%,Start,Time,Plays,Yds.4,Pts
0,Team Stats,441,6180,1056.0,5.9,11,9,351,368.0,550,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Opp. Stats,250,5223,998.0,5.2,23,10,294,368.0,596,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Lg Rank Offense,3,4,NaN,NaN,1,13,5,NaN,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Lg Rank Defense,1,8,NaN,NaN,14,9,3,NaN,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
nwe1 = pd.DataFrame(nwe[1])

In [28]:
nwe1.head()

,Unnamed: 0,Score,Offense,Defense,Expected Points,Week,Day,Date,Unnamed: 8,Unnamed: 9,...,RushY,TO,1stD.1,TotYd.1,PassY.1,RushY.1,TO.1,Offense.1,Defense.1,Sp. Tms
0,1,NaN,September 11,7:30PM ET,boxscore,W,NaN,1-0,@,Arizona Cardinals,...,92.0,NaN,5.61,-11.42,9.08,NaN,NaN,NaN,NaN,NaN
1,2,NaN,September 18,1:02PM ET,boxscore,W,NaN,2-0,NaN,Miami Dolphins,...,70.0,4.0,17.47,-6.98,-3.95,NaN,NaN,NaN,NaN,NaN
2,3,NaN,September 22,8:26PM ET,boxscore,W,NaN,3-0,NaN,Houston Texans,...,109.0,3.0,1.19,14.60,10.11,NaN,NaN,NaN,NaN,NaN
3,4,NaN,October 2,1:02PM ET,boxscore,L,NaN,3-1,NaN,Buffalo Bills,...,134.0,NaN,-10.11,-6.11,3.66,NaN,NaN,NaN,NaN,NaN
4,5,NaN,October 9,1:02PM ET,boxscore,W,NaN,4-1,@,Cleveland Browns,...,27.0,1.0,17.05,4.26,-3.15,NaN,NaN,NaN,NaN,NaN

In [33]:
column_list = nwe1.columns

In [34]:
column_list

Index(['Unnamed: 0', 'Score', 'Offense', 'Defense', 'Expected Points', 'Week',
       'Day', 'Date', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'OT', 'Rec',
       'Unnamed: 13', 'Opp', 'Tm', 'Opp.1', '1stD', 'TotYd', 'PassY', 'RushY',
       'TO', '1stD.1', 'TotYd.1', 'PassY.1', 'RushY.1', 'TO.1', 'Offense.1',
       'Defense.1', 'Sp. Tms'],
      dtype='object')

In [44]:
column_list[0]

'Unnamed: 0'

In [60]:
row1 = nwe1[:1]

row1 = row1.isnull()

In [68]:
row1.T

                     0
Unnamed: 0       False
Score             True
Offense          False
Defense          False
Expected Points  False
Week             False
Day               True
Date             False
Unnamed: 8       False
Unnamed: 9       False
Unnamed: 10      False
OT               False
Rec              False
Unnamed: 13      False
Opp              False
Tm               False
Opp.1            False
1stD             False
TotYd            False
PassY            False
RushY            False
TO                True
1stD.1           False
TotYd.1          False
PassY.1          False
RushY.1           True
TO.1              True
Offense.1         True
Defense.1         True
Sp. Tms           True

In [31]:
nwe1.drop('Score', axis=1, inplace=True)
nwe1.drop('Expected Points', axis=1, inplace=True)
nwe1.drop('Day', axis=1, inplace=True)

,Unnamed: 0,Offense,Defense,Expected Points,Week,Day,Date,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,RushY,TO,1stD.1,TotYd.1,PassY.1,RushY.1,TO.1,Offense.1,Defense.1,Sp. Tms
0,1,September 11,7:30PM ET,boxscore,W,NaN,1-0,@,Arizona Cardinals,23.0,...,92.0,NaN,5.61,-11.42,9.08,NaN,NaN,NaN,NaN,NaN
1,2,September 18,1:02PM ET,boxscore,W,NaN,2-0,NaN,Miami Dolphins,31.0,...,70.0,4.0,17.47,-6.98,-3.95,NaN,NaN,NaN,NaN,NaN
2,3,September 22,8:26PM ET,boxscore,W,NaN,3-0,NaN,Houston Texans,27.0,...,109.0,3.0,1.19,14.60,10.11,NaN,NaN,NaN,NaN,NaN
3,4,October 2,1:02PM ET,boxscore,L,NaN,3-1,NaN,Buffalo Bills,0.0,...,134.0,NaN,-10.11,-6.11,3.66,NaN,NaN,NaN,NaN,NaN
4,5,October 9,1:02PM ET,boxscore,W,NaN,4-1,@,Cleveland Browns,33.0,...,27.0,1.0,17.05,4.26,-3.15,NaN,NaN,NaN,NaN,NaN
5,6,October 16,1:02PM ET,boxscore,W,NaN,5-1,NaN,Cincinnati Bengals,35.0,...,120.0,NaN,21.68,-8.15,3.28,NaN,NaN,NaN,NaN,NaN
6,7,October 23,4:25PM ET,boxscore,W,NaN,6-1,@,Pittsburgh Steelers,27.0,...,94.0,1.0,12.52,4.28,-6.81,NaN,NaN,NaN,NaN,NaN
7,8,October 30,1:02PM ET,boxscore,W,NaN,7-1,@,Buffalo Bills,41.0,...,167.0,NaN,22.71,-13.72,6.16,NaN,NaN,NaN,NaN,NaN
8,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bye Week,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,November 13,8:30PM ET,boxscore,L,NaN,7-2,NaN,Seattle Seahawks,24.0,...,96.0,NaN,11.93,-17.85,-1.92,NaN,NaN,NaN,NaN,NaN
10,11,November 20,4:25PM ET,boxscore,W,NaN,8-2,@,San Francisco 49ers,30.0,...,122.0,NaN,17.09,-1.68,1.82,NaN,NaN,NaN,NaN,NaN
11,12,November 27,4:25PM ET,boxscore,W,NaN,9-2,@,New York Jets,22.0,...,64.0,2.0,11.44,-0.93,-2.73,NaN,NaN,NaN,NaN,NaN
12,13,December 4,1:00PM ET,boxscore,W,NaN,10-2,NaN,Los Angeles Rams,26.0,...,36.0,2.0,3.25,18.27,-6.34,NaN,NaN,NaN,NaN,NaN
13,14,December 12,8:30PM ET,boxscore,W,NaN,11-2,NaN,Baltimore Ravens,30.0,...,42.0,1.0,16.83,2.31,-8.57,NaN,NaN,NaN,NaN,NaN
14,15,December 18,4:25PM ET,boxscore,W,NaN,12-2,@,Denver Broncos,16.0,...,58.0,3.0,-4.97,14.82,2.33,NaN,NaN,NaN,NaN,NaN
15,16,December 24,1:00PM ET,boxscore,W,NaN,13-2,NaN,New York Jets,41.0,...,111.0,4.0,16.02,18.13,2.07,NaN,NaN,NaN,NaN,NaN
16,17,January 1,1:00PM ET,boxscore,W,NaN,14-2,@,Miami Dolphins,35.0,...,75.0,2.0,19.55,3.73,-6.78,NaN,NaN,NaN,NaN,NaN
17,NaN,Playoffs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Division,January 14,8:15PM ET,preview,NaN,NaN,NaN,NaN,Houston Texans,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
nwe1['OT']

0     21.0
1     24.0
2      0.0
3     16.0
4     13.0
5     17.0
6     16.0
7     25.0
8      NaN
9     31.0
10    17.0
11    17.0
12    10.0
13    23.0
14     3.0
15     3.0
16    14.0
17     NaN
18     NaN
Name: OT, dtype: float64

In [73]:
nwe2 = nwe1.loc[:,['Unnamed: 9', 'Unnamed: 10', 'OT']]

             Unnamed: 9  Unnamed: 10    OT
0     Arizona Cardinals         23.0  21.0
1        Miami Dolphins         31.0  24.0
2        Houston Texans         27.0   0.0
3         Buffalo Bills          0.0  16.0
4      Cleveland Browns         33.0  13.0
5    Cincinnati Bengals         35.0  17.0
6   Pittsburgh Steelers         27.0  16.0
7         Buffalo Bills         41.0  25.0
9      Seattle Seahawks         24.0  31.0
10  San Francisco 49ers         30.0  17.0
11        New York Jets         22.0  17.0
12     Los Angeles Rams         26.0  10.0
13     Baltimore Ravens         30.0  23.0
14       Denver Broncos         16.0   3.0
15        New York Jets         41.0   3.0
16       Miami Dolphins         35.0  14.0

In [77]:
nwe2 = nwe2.rename(columns={'Unnamed: 9': 'Opponent', 'Unnamed: 10': 'PtsFor', 'OT': 'PtsAg'})

In [79]:
nwe2 = nwe2.dropna(axis=0)
nwe2

               Opponent  PtsFor  PtsAg
0     Arizona Cardinals    23.0   21.0
1        Miami Dolphins    31.0   24.0
2        Houston Texans    27.0    0.0
3         Buffalo Bills     0.0   16.0
4      Cleveland Browns    33.0   13.0
5    Cincinnati Bengals    35.0   17.0
6   Pittsburgh Steelers    27.0   16.0
7         Buffalo Bills    41.0   25.0
9      Seattle Seahawks    24.0   31.0
10  San Francisco 49ers    30.0   17.0
11        New York Jets    22.0   17.0
12     Los Angeles Rams    26.0   10.0
13     Baltimore Ravens    30.0   23.0
14       Denver Broncos    16.0    3.0
15        New York Jets    41.0    3.0
16       Miami Dolphins    35.0   14.0

In [81]:
print (nwe2.PtsFor.mean())
print (nwe2.PtsAg.mean())

27.5625
15.625